

spring.datasource.url=jdbc:mysql://localhost:3306/fuel
#spring.datasource.driverDto-class-name=org.h2.DriverDto
spring.datasource.username=root
spring.datasource.password=root
spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=validate
  //update
spring.h2.console.path=/h2-console

//spring.sql.init.mode=never

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml